<h2>In-class transcript from Lecture 8, February 4, 2019</h2> 


# Imports and defs for lecture

In [1]:
# These are the standard imports for CS 111. 
# This list may change as the quarter goes on.

import os
import time
import math
import struct
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import sparse
from scipy import linalg
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
%matplotlib tk

In [2]:
bits = {'0':'0000', '1':'0001', '2':'0010', '3':'0011', 
        '4':'0100', '5':'0101', '6':'0110', '7':'0111', 
        '8':'1000', '9':'1001', 'a':'1010', 'b':'1011', 
        'c':'1100', 'd':'1101', 'e':'1110', 'f':'1111'}

drop = {'0':'0', '1':'1', '2':'2', '3':'3', '4':'4', '5':'5', '6':'6', '7':'7', 
        '8':'0', '9':'1', 'a':'2', 'b':'3', 'c':'4', 'd':'5', 'e':'6', 'f':'7'}

def double_to_hex(f):
    return hex(struct.unpack('<Q', struct.pack('<d', f))[0])

def fprint(x):
    """Print a 64-bit floating-point number in various formats.
    """
    print('input     :', x)
    # Cast the input to a 64-bit float
    x = np.float64(x)
    xhex = double_to_hex(x)[2:]
    print('as float64: {:.16e}'.format(x))
    print('as hex    : ' + xhex)
    if bits[xhex[0]][0] == '0':
        sign = '0 means +'
    else:
        sign = '1 means -'
    print('sign      :', sign)
    expostr = drop[xhex[0]] + xhex[1:3]
    expo = int(expostr, 16)
    if expo == 0:
        print('exponent  :', expostr, 'means zero or denormal')
    elif expo == 2047:
        print('exponent  :', expostr, 'means inf or nan')
    else:
        print('exponent  :', expostr, 'means', expo, '- 1023 =', expo - 1023)
        mantissa = '1.'
        for i in range(3,16):
            mantissa = mantissa + bits[xhex[i]]
        print('mantissa  :', mantissa)
    print()


# Lecture starts here

In [3]:
# Matrix condition number

A = np.array([[1,1000],[2,2001]])
A

array([[   1, 1000],
       [   2, 2001]])

In [4]:
b1 = np.array([1.0,2.0])
b1

array([1., 2.])

In [5]:
x1 = npla.solve(A,b1)
x1

array([ 1., -0.])

In [6]:
b2 = np.array([1.0,2.001])


In [7]:
x2 = npla.solve(A,b2)
x2

array([1.10134124e-13, 1.00000000e-03])

In [8]:
npla.norm(x2-x1)

1.000000499999765

In [9]:
npla.norm(b1 - A@x2)

0.0009999999999998899

In [10]:
npla.cond(A)

5004005.999995576

In [11]:
# Floating point arithmetic

bits

{'0': '0000',
 '1': '0001',
 '2': '0010',
 '3': '0011',
 '4': '0100',
 '5': '0101',
 '6': '0110',
 '7': '0111',
 '8': '1000',
 '9': '1001',
 'a': '1010',
 'b': '1011',
 'c': '1100',
 'd': '1101',
 'e': '1110',
 'f': '1111'}

In [12]:
1.0 +  .25

1.25

In [13]:
x = 1.0
for i in range(60):
    print(x)
    print(1+x)
    print()
    if 1.0 == (1.0+x): break
    x = x/2.

1.0
2.0

0.5
1.5

0.25
1.25

0.125
1.125

0.0625
1.0625

0.03125
1.03125

0.015625
1.015625

0.0078125
1.0078125

0.00390625
1.00390625

0.001953125
1.001953125

0.0009765625
1.0009765625

0.00048828125
1.00048828125

0.000244140625
1.000244140625

0.0001220703125
1.0001220703125

6.103515625e-05
1.00006103515625

3.0517578125e-05
1.000030517578125

1.52587890625e-05
1.0000152587890625

7.62939453125e-06
1.0000076293945312

3.814697265625e-06
1.0000038146972656

1.9073486328125e-06
1.0000019073486328

9.5367431640625e-07
1.0000009536743164

4.76837158203125e-07
1.0000004768371582

2.384185791015625e-07
1.000000238418579

1.1920928955078125e-07
1.0000001192092896

5.960464477539063e-08
1.0000000596046448

2.9802322387695312e-08
1.0000000298023224

1.4901161193847656e-08
1.0000000149011612

7.450580596923828e-09
1.0000000074505806

3.725290298461914e-09
1.0000000037252903

1.862645149230957e-09
1.0000000018626451

9.313225746154785e-10
1.0000000009313226

4.656612873077393e-10
1.00000000

In [14]:
fprint(1.0)

input     : 1.0
as float64: 1.0000000000000000e+00
as hex    : 3ff0000000000000
sign      : 0 means +
exponent  : 3ff means 1023 - 1023 = 0
mantissa  : 1.0000000000000000000000000000000000000000000000000000



In [15]:
fprint(2.)

input     : 2.0
as float64: 2.0000000000000000e+00
as hex    : 4000000000000000
sign      : 0 means +
exponent  : 400 means 1024 - 1023 = 1
mantissa  : 1.0000000000000000000000000000000000000000000000000000



In [16]:
fprint(1./8.)

input     : 0.125
as float64: 1.2500000000000000e-01
as hex    : 3fc0000000000000
sign      : 0 means +
exponent  : 3fc means 1020 - 1023 = -3
mantissa  : 1.0000000000000000000000000000000000000000000000000000



In [17]:
fprint(0.)

input     : 0.0
as float64: 0.0000000000000000e+00
as hex    : 0
sign      : 0 means +
exponent  : 0 means zero or denormal



In [18]:
fprint(1./3.)

input     : 0.3333333333333333
as float64: 3.3333333333333331e-01
as hex    : 3fd5555555555555
sign      : 0 means +
exponent  : 3fd means 1021 - 1023 = -2
mantissa  : 1.0101010101010101010101010101010101010101010101010101



In [19]:
fprint(np.inf)

input     : inf
as float64: inf
as hex    : 7ff0000000000000
sign      : 0 means +
exponent  : 7ff means inf or nan



In [20]:
fprint(-np.inf)

input     : -inf
as float64: -inf
as hex    : fff0000000000000
sign      : 1 means -
exponent  : 7ff means inf or nan



In [21]:
fprint(np.nan)

input     : nan
as float64: nan
as hex    : 7ff8000000000000
sign      : 0 means +
exponent  : 7ff means inf or nan



In [22]:
a = 1/10
fprint(a)
fprint(a+a+a+a+a+a+a+a+a+a)

input     : 0.1
as float64: 1.0000000000000001e-01
as hex    : 3fb999999999999a
sign      : 0 means +
exponent  : 3fb means 1019 - 1023 = -4
mantissa  : 1.1001100110011001100110011001100110011001100110011010

input     : 0.9999999999999999
as float64: 9.9999999999999989e-01
as hex    : 3fefffffffffffff
sign      : 0 means +
exponent  : 3fe means 1022 - 1023 = -1
mantissa  : 1.1111111111111111111111111111111111111111111111111111



In [23]:
print(np.finfo(np.float64))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------



In [24]:
2**53 / 10**16

0.9007199254740992

In [25]:
x = 1.0
for i in range(60):
    print('x:')
    fprint(x)
    print('1 + x:')
    fprint(1+x)
    if 1.0 == (1.0+x): break
    x = x/2.

x:
input     : 1.0
as float64: 1.0000000000000000e+00
as hex    : 3ff0000000000000
sign      : 0 means +
exponent  : 3ff means 1023 - 1023 = 0
mantissa  : 1.0000000000000000000000000000000000000000000000000000

1 + x:
input     : 2.0
as float64: 2.0000000000000000e+00
as hex    : 4000000000000000
sign      : 0 means +
exponent  : 400 means 1024 - 1023 = 1
mantissa  : 1.0000000000000000000000000000000000000000000000000000

x:
input     : 0.5
as float64: 5.0000000000000000e-01
as hex    : 3fe0000000000000
sign      : 0 means +
exponent  : 3fe means 1022 - 1023 = -1
mantissa  : 1.0000000000000000000000000000000000000000000000000000

1 + x:
input     : 1.5
as float64: 1.5000000000000000e+00
as hex    : 3ff8000000000000
sign      : 0 means +
exponent  : 3ff means 1023 - 1023 = 0
mantissa  : 1.1000000000000000000000000000000000000000000000000000

x:
input     : 0.25
as float64: 2.5000000000000000e-01
as hex    : 3fd0000000000000
sign      : 0 means +
exponent  : 3fd means 1021 - 1023 = -2
ma