<h2>In-class transcript from Lecture 9, February 11, 2019</h2> 


# Imports and defs for lecture

In [1]:
# These are the standard imports for CS 111. 
# This list may change as the quarter goes on.

import os
import math
import time
import struct
import json
import pandas as pd
import networkx as nx
import numpy as np
import numpy.linalg as npla
import scipy
import scipy.sparse.linalg as spla
from scipy import sparse
from scipy import linalg
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
%matplotlib tk


In [3]:
np.set_printoptions(precision = 4)

# Lecture starts here

In [4]:
A = np.random.randn(4,4)
A

array([[ 1.4877, -0.0246,  1.4312, -0.6387],
       [ 0.0605, -1.125 , -0.1555, -0.5861],
       [-1.1011, -0.7383, -0.905 , -1.5657],
       [-1.2705, -1.2278,  0.3275, -1.4199]])

In [7]:
help(linalg.eig)

In [8]:
d, V = linalg.eig(A)

In [9]:
print(d)

[ 1.5629+0.j     -0.9138+0.8855j -0.9138-0.8855j -1.6975+0.j    ]


In [10]:
print(V)

[[ 0.8764+0.j     -0.3201-0.2216j -0.3201+0.2216j -0.2659+0.j    ]
 [ 0.1244+0.j      0.1807+0.2906j  0.1807-0.2906j  0.5408+0.j    ]
 [-0.1486+0.j      0.7417+0.j      0.7417-0.j      0.7373+0.j    ]
 [-0.4408+0.j      0.1441-0.4006j  0.1441+0.4006j  0.3052+0.j    ]]


In [13]:
npla.norm(A @ V[:,0] - d[0] * V[:,0])

7.473417450352271e-16

In [14]:
npla.norm(A @ V[:,2] - d[2] * V[:,2])

1.5476066938469756e-15

In [17]:
npla.norm(A @ V - V * d)

3.020005603412052e-15

In [18]:
A

array([[ 1.4877, -0.0246,  1.4312, -0.6387],
       [ 0.0605, -1.125 , -0.1555, -0.5861],
       [-1.1011, -0.7383, -0.905 , -1.5657],
       [-1.2705, -1.2278,  0.3275, -1.4199]])

In [19]:
A.T

array([[ 1.4877,  0.0605, -1.1011, -1.2705],
       [-0.0246, -1.125 , -0.7383, -1.2278],
       [ 1.4312, -0.1555, -0.905 ,  0.3275],
       [-0.6387, -0.5861, -1.5657, -1.4199]])

In [20]:
dt, Vt = linalg.eig(A.T)

In [23]:
Vt

array([[-0.8133+0.j    , -0.107 +0.j    , -0.0605-0.2258j,
        -0.0605+0.2258j],
       [-0.0633+0.j    , -0.8057+0.j    ,  0.5843+0.j    ,
         0.5843-0.j    ],
       [-0.414 +0.j    ,  0.2522+0.j    , -0.545 +0.1213j,
        -0.545 -0.1213j],
       [ 0.4039+0.j    , -0.5252+0.j    ,  0.2284-0.4899j,
         0.2284+0.4899j]])

In [22]:
V

array([[ 0.8764+0.j    , -0.3201-0.2216j, -0.3201+0.2216j,
        -0.2659+0.j    ],
       [ 0.1244+0.j    ,  0.1807+0.2906j,  0.1807-0.2906j,
         0.5408+0.j    ],
       [-0.1486+0.j    ,  0.7417+0.j    ,  0.7417-0.j    ,
         0.7373+0.j    ],
       [-0.4408+0.j    ,  0.1441-0.4006j,  0.1441+0.4006j,
         0.3052+0.j    ]])

In [24]:
d

array([ 1.5629+0.j    , -0.9138+0.8855j, -0.9138-0.8855j, -1.6975+0.j    ])

In [25]:
dt

array([ 1.5629+0.j    , -1.6975+0.j    , -0.9138+0.8855j, -0.9138-0.8855j])

In [26]:
B = A + A.T
B

array([[ 2.9754,  0.0359,  0.3301, -1.9092],
       [ 0.0359, -2.25  , -0.8938, -1.8139],
       [ 0.3301, -0.8938, -1.81  , -1.2382],
       [-1.9092, -1.8139, -1.2382, -2.8399]])

In [27]:
B - B.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
dB, vB = linalg.eig(B)

In [29]:
dB

array([ 3.6724+0.j, -5.2683+0.j, -1.3357+0.j, -0.9928+0.j])

In [30]:
vB

array([[ 0.9363,  0.1501, -0.273 , -0.1619],
       [ 0.0865,  0.5489,  0.1097,  0.8242],
       [ 0.1146,  0.3873,  0.8319, -0.3807],
       [-0.3204,  0.7254, -0.4706, -0.3868]])

In [31]:
dB, vB = linalg.eigh(B)

In [32]:
dB

array([-5.2683, -1.3357, -0.9928,  3.6724])

# Page Rank example starts here

In [34]:
E = np.load('PageRankEG1.npy')
E

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [35]:
E.shape

(4, 4)

In [36]:
indegree = np.sum(E,1)
indegree

array([2., 1., 3., 2.])

In [37]:
np.sort(indegree)

array([1., 2., 2., 3.])

In [46]:
deg_sort = np.argsort(indegree)
deg_sort

array([1, 0, 3, 2])

In [47]:
indegree

array([2., 1., 3., 2.])

In [48]:
indegree[deg_sort]

array([1., 2., 2., 3.])

In [49]:
deg_sort = np.argsort(indegree)[::-1]
deg_sort

array([2, 3, 0, 1])

In [50]:
indegree[deg_sort]

array([3., 2., 2., 1.])