<h2>Lecture 2 : Interesting Matrices</h2>


In [1]:
# These are the standard imports for CS 111. 
# This list may change as the quarter goes on.

import os
import time
import math
import numpy as np
import scipy
from scipy import sparse
from scipy import linalg
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
%matplotlib tk

In [3]:
A = np.array(range(25)).reshape(5,5)
print(A,'\n')
I = np.eye(5)
print(I,'\n')
print( A @ I, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]] 



In [4]:
D = np.diag([2,1,1,0,3])
print(D,'\n')

[[2 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 3]] 



In [5]:
print(A,'\n')
print( A @ D, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  0 12]
 [10  6  7  0 27]
 [20 11 12  0 42]
 [30 16 17  0 57]
 [40 21 22  0 72]] 



In [6]:
print(A,'\n')
print( D @ A, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  2  4  6  8]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  0  0  0  0]
 [60 63 66 69 72]] 



In [7]:
P = np.eye(5)
print(P,'\n')
P[0,0]=0
P[0,1]=1
P[1,0]=1
P[1,1]=0
print(P,'\n')

print(A,'\n')
print(P @ A,'\n')
print(A @ P,'\n')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]] 

[[ 1.  0.  2.  3.  4.]
 [ 6.  5.  7.  8.  9.]
 [11. 10. 12. 13. 14.]
 [16. 15. 17. 18. 19.]
 [21. 20. 22. 23. 24.]] 



In [8]:
print(A,'\n')
B = A[3,4]
print(B,'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

19 



In [9]:
print(A,'\n')
B = A[3,:]
print(B,'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[15 16 17 18 19] 



In [10]:
print(A,'\n')
B = A[[1,0,2,3,4],:]
print(B,'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 



In [11]:
print(A,'\n')
vec = np.array([1,0,2,3,4])
B = np.eye(5)
print(B,'\n')
print(B[vec,:],'\n')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 



In [12]:
vec = np.random.permutation(5)
I = np.eye(5)

P = I[vec,:]
P

array([[0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [13]:
print(P @ A,'\n')
print(A @ P.T,'\n')
vec =[3,1,2,4,0]
print(A[vec,:],'\n')
print(A[:,vec],'\n')

[[20. 21. 22. 23. 24.]
 [ 5.  6.  7.  8.  9.]
 [ 0.  1.  2.  3.  4.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]] 

[[ 4.  1.  0.  2.  3.]
 [ 9.  6.  5.  7.  8.]
 [14. 11. 10. 12. 13.]
 [19. 16. 15. 17. 18.]
 [24. 21. 20. 22. 23.]] 

[[15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [ 0  1  2  3  4]] 

[[ 3  1  2  4  0]
 [ 8  6  7  9  5]
 [13 11 12 14 10]
 [18 16 17 19 15]
 [23 21 22 24 20]] 



In [14]:
P @ P.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])