Computing some of the answers to the first-day quiz in CS111.

In [1]:
import math
import matplotlib.pyplot as plt
import numpy as np
import numpy.linalg as la
import pandas as pd
import scipy as sp
import scipy.sparse as sps
import sklearn as sk
%matplotlib tk

In [14]:
print('\nQuiz problem 1\n')
A = np.array([[3, -1, 2], [0, 1, 2], [1, 0, -1]])
print (A)
print()
print (A.T)
print()
print (A @ A)
print()
print (A.T @ A)

print('\nQuiz problem 2\n')
x = np.array([3, 1, 4, 1, 5])
print(x)
print()
print(np.linalg.norm(x))

print('\nQuiz problem 3\n')
A = np.array([[2, -3, 1], [0, 2, 3], [1, 0, 1]])
b = np.array([1, 7, 4])
print(A)
print()
print(b)

print('\nQuiz problem 4\n')
x = la.solve(A,b)
print(x)

print('\nQuiz problem 5\n')
A = np.array([[1, 2], [2, 4]])
b = np.array([3, 3])
print(A)
print()
print(b)
print()
try:
    x = la.solve(A,b)
except:
    print('solve failed')

    
print('\nQuiz problem 6\n')
b = np.array([3, 6])
x1 = np.array([1, 1])
x2 = np.array([3, 0])
print(A)
print()
print(b)
print()
print(x1)
print()
print(A@x1 - b)
print()
print(x2)
print()
print(A@x2 - b)

print('\nQuiz problem 8\n')
A = np.array([[4, -1], [-1, 4]])
print(A)
print()
lam, V = la.eig(A)
print(lam)
print()
print(V)

print('\nQuiz problem 12\n')
t = np.array([0, 40, 80])
h = 1280*t - 16*t**2
print(t, h)



Quiz problem 1

[[ 3 -1  2]
 [ 0  1  2]
 [ 1  0 -1]]

[[ 3  0  1]
 [-1  1  0]
 [ 2  2 -1]]

[[11 -4  2]
 [ 2  1  0]
 [ 2 -1  3]]

[[10 -3  5]
 [-3  2  0]
 [ 5  0  9]]

Quiz problem 2

[3 1 4 1 5]

7.211102550927978

Quiz problem 3

[[ 2 -3  1]
 [ 0  2  3]
 [ 1  0  1]]

[1 7 4]

Quiz problem 4

[3. 2. 1.]

Quiz problem 5

[[1 2]
 [2 4]]

[3 3]

solve failed

Quiz problem 6

[[1 2]
 [2 4]]

[3 6]

[1 1]

[0 0]

[3 0]

[0 0]

Quiz problem 8

[[ 4 -1]
 [-1  4]]

[5. 3.]

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Quiz problem 12

[ 0 40 80] [    0 25600     0]
