<h2>In-class transcript from Lecture 6, January 28, 2019</h2> 


# Imports and defs for lecture

In [1]:
# These are the standard imports for CS 111. 
# This list may change as the quarter goes on.

import os
import time
import math
import numpy as np
import numpy.linalg as npla
import scipy
from scipy import sparse
from scipy import linalg
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d
%matplotlib tk

In [2]:
def Usolve(U, y, unit_diag = False):
    """Backward solve an upper triangular system Ux = y for x
    Parameters: 
      U: the matrix, must be square, upper triangular, with nonzeros on the diagonal
      y: the right-hand side vector
      unit_diag = False: if true, assume the diagonal is all ones
    Output:
      x: the solution vector to U @ x == y
    """
    # Check the input
    m, n = U.shape
    assert m == n, "matrix must be square"
    assert np.all(np.triu(U) == U), "matrix U must be upper triangular"
    if unit_diag:
        assert np.all(np.diag(U) == 1), "matrix U must have ones on the diagonal"
    yn, = y.shape
    assert yn == n, "rhs vector must be same size as U"
    
    # Make a copy of y that we will transform into the solution
    x = y.astype(np.float64).copy()
    
    # Back solve
    for col in reversed(range(n)):
        if not unit_diag:
            x[col] /= U[col, col]
        x[:col] -= x[col] * U[:col, col]
        
    return x

# Lecture starts here

In [3]:
A = np.round(20*np.random.rand(4,4))
A


array([[11., 18., 17.,  6.],
       [ 9.,  9., 13., 16.],
       [12.,  5.,  4., 11.],
       [ 6., 14.,  0., 12.]])

In [4]:
Q, R = linalg.qr(A)

In [9]:

print('Q:', Q.shape); print(Q)
print('\nR:', R.shape); print(R)
npla.norm(Q @ R - A )

Q: (4, 4)
[[-0.56280896  0.46355227  0.42690992 -0.53489558]
 [-0.46048006 -0.07694592  0.43861196  0.76789126]
 [-0.61397341 -0.66019186 -0.37114433 -0.22234039]
 [-0.30698671  0.58595676 -0.69829747  0.27348579]]

R: (4, 4)
[[-19.54482029 -21.64256278 -18.00988676 -21.18208272]
 [  0.          12.55386301   4.2393242    1.31954961]
 [  0.           0.          11.47484681  -2.88290642]
 [  0.           0.           0.           9.91297186]]


2.1302399764542657e-14

In [8]:
Q.T @ Q

array([[ 1.00000000e+00, -1.11022302e-16, -8.50014503e-17,
         1.11022302e-16],
       [-1.11022302e-16,  1.00000000e+00,  1.11022302e-16,
        -5.55111512e-17],
       [-8.50014503e-17,  1.11022302e-16,  1.00000000e+00,
         0.00000000e+00],
       [ 1.11022302e-16, -5.55111512e-17,  0.00000000e+00,
         1.00000000e+00]])

In [10]:
b = np.random.rand(4)
b

array([0.9189543 , 0.17420997, 0.80072507, 0.74870822])

In [11]:
x = Usolve(R, Q.T @ b)
x

array([ 0.09268061,  0.0423831 , -0.03900346, -0.0333949 ])

In [13]:
npla.norm(b - A @ x) / npla.norm(b)

7.309037829299854e-16

In [14]:
A = np.round(20*np.random.rand(10,4))
A


array([[14.,  9.,  0.,  2.],
       [ 0.,  3.,  6., 10.],
       [20.,  9., 16., 10.],
       [ 7., 19.,  1.,  6.],
       [ 3., 16.,  7., 18.],
       [ 1., 15., 11., 14.],
       [10., 12.,  7.,  9.],
       [ 6., 15.,  1., 16.],
       [18., 19.,  9., 19.],
       [ 3., 15., 16.,  6.]])

In [15]:
Q, R = linalg.qr(A)

In [17]:
npla.norm(Q.T @ Q - np.eye(10))


6.942194939621275e-16

In [18]:
R

array([[-33.52610923, -32.78042175, -19.23873706, -26.36750939],
       [  0.        , -29.89053279, -11.28605127, -22.90564463],
       [  0.        ,   0.        , -18.77487798,  -4.59167513],
       [  0.        ,   0.        ,   0.        ,  15.90604954],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ]])

In [19]:
npla.norm(Q @ R - A )

1.0088378597433515e-14